import type { User, Task, TaskHistory, Comment, Template } from '../types/index'

export const users: User[] = [
  { id: 'u1', name: '박지수', email: 'jisoo.park@telecom.co.kr', role: 'admin' },
  { id: 'u2', name: '김민준', email: 'minjun.kim@telecom.co.kr', role: 'assignee' },
  { id: 'u3', name: '이서연', email: 'seoyeon.lee@telecom.co.kr', role: 'assignee' },
  { id: 'u4', name: '최도현', email: 'dohyun.choi@telecom.co.kr', role: 'assignee' },
  { id: 'u5', name: '정유진', email: 'yujin.jung@telecom.co.kr', role: 'assignee' },
  { id: 'u6', name: '강현우', email: 'hyunwoo.kang@telecom.co.kr', role: 'assignee' },
]

export const tasks: Task[] = [
  {
    id: 't1',
    title: '요금제 노출 순서 설정',
    description: 'PRD 환경 메인 요금제 목록의 노출 순서를 변경합니다. 5G Ultimate 요금제가 최상단에 오도록 정렬 기준값을 수정해주세요.',
    assigneeId: 'u2',
    status: 'in_progress',
    environment: 'prd',
    dueDate: '2026-07-15',
    isBlocking: true,
    confluenceUrl: 'https://confluence.example.com/pages/1001',
    verifyUrl: 'https://admin.prd.telecom.co.kr/plans/order',
    verifyPoint: '요금제 목록 화면에서 5G Ultimate 요금제가 1번 위치에 있는지 확인',
    screenshotUrl: null,
    createdAt: '2026-07-01T09:00:00Z',
    updatedAt: '2026-07-10T14:30:00Z',
  },
  {
    id: 't2',
    title: '가입 가능 연령 제한 값 등록',
    description: '청소년 전용 요금제의 가입 가능 최대 연령을 24세에서 18세로 변경합니다.',
    assigneeId: 'u3',
    status: 'review_requested',
    environment: 'stg',
    dueDate: '2026-07-18',
    isBlocking: true,
    confluenceUrl: 'https://confluence.example.com/pages/1002',
    verifyUrl: 'https://admin.stg.telecom.co.kr/plans/youth/age-limit',
    verifyPoint: '청소년 요금제 가입 조건에서 최대 연령이 18세로 표시되는지 확인',
    screenshotUrl: null,
    createdAt: '2026-07-05T10:00:00Z',
    updatedAt: '2026-07-17T16:00:00Z',
  },
  {
    id: 't3',
    title: '프로모션 배너 노출 기간 설정',
    description: '여름 특가 프로모션 배너의 노출 시작일과 종료일을 설정합니다. 시작 07/25, 종료 08/15.',
    assigneeId: 'u4',
    status: 'todo',
    environment: 'dev',
    dueDate: '2026-07-20',
    isBlocking: false,
    confluenceUrl: null,
    verifyUrl: null,
    verifyPoint: null,
    screenshotUrl: null,
    createdAt: '2026-07-08T11:00:00Z',
    updatedAt: '2026-07-08T11:00:00Z',
  },
  {
    id: 't4',
    title: '부가서비스 자동 해지 임계값 설정',
    description: '사용량이 일정 기준 이하인 부가서비스의 자동 해지 트리거 값을 조정합니다. 현행 5회에서 3회로 변경.',
    assigneeId: 'u5',
    status: 'in_progress',
    environment: 'prd',
    dueDate: '2026-07-22',
    isBlocking: false,
    confluenceUrl: 'https://confluence.example.com/pages/1004',
    verifyUrl: 'https://admin.prd.telecom.co.kr/addons/auto-cancel',
    verifyPoint: '자동 해지 설정 페이지에서 임계값이 3회로 변경되었는지 확인',
    screenshotUrl: null,
    createdAt: '2026-07-10T09:00:00Z',
    updatedAt: '2026-07-15T10:00:00Z',
  },
  {
    id: 't5',
    title: '로밍 요금제 가격 정보 업데이트',
    description: '동남아 7개국 로밍 요금제의 일일 이용 요금을 신규 협약 금액으로 업데이트합니다.',
    assigneeId: 'u6',
    status: 'todo',
    environment: 'stg',
    dueDate: '2026-07-23',
    isBlocking: false,
    confluenceUrl: 'https://confluence.example.com/pages/1005',
    verifyUrl: null,
    verifyPoint: null,
    screenshotUrl: null,
    createdAt: '2026-07-11T14:00:00Z',
    updatedAt: '2026-07-11T14:00:00Z',
  },
  {
    id: 't6',
    title: '기기변경 할인 조건 설정',
    description: '24개월 이상 사용 고객 대상 기기변경 할인 조건을 설정합니다. 10% 할인 적용.',
    assigneeId: 'u2',
    status: 'done',
    environment: 'prd',
    dueDate: null,
    isBlocking: false,
    confluenceUrl: 'https://confluence.example.com/pages/1006',
    verifyUrl: 'https://admin.prd.telecom.co.kr/discounts/device-change',
    verifyPoint: '기기변경 화면에서 24개월 이상 고객에게 10% 할인이 적용되는지 확인',
    screenshotUrl: null,
    createdAt: '2026-07-02T09:00:00Z',
    updatedAt: '2026-07-12T16:00:00Z',
  },
  {
    id: 't7',
    title: '무약정 전환 가능 시점 설정',
    description: '약정 만료 전 무약정 전환 신청 가능 시작 시점을 만료 30일 전으로 설정합니다.',
    assigneeId: 'u4',
    status: 'review_requested',
    environment: 'stg',
    dueDate: '2026-07-25',
    isBlocking: true,
    confluenceUrl: 'https://confluence.example.com/pages/1007',
    verifyUrl: 'https://admin.stg.telecom.co.kr/plans/no-contract/transfer',
    verifyPoint: '약정 만료 30일 전 고객의 무약정 전환 메뉴가 활성화되어 있는지 확인',
    screenshotUrl: null,
    createdAt: '2026-07-06T10:00:00Z',
    updatedAt: '2026-07-20T11:00:00Z',
  },
  {
    id: 't8',
    title: '결합 할인 적용 대상 그룹 등록',
    description: '가족 결합 3인 이상 그룹에 신규 할인율을 적용하는 대상 그룹을 BO에 등록합니다.',
    assigneeId: 'u3',
    status: 'todo',
    environment: 'dev',
    dueDate: '2026-07-28',
    isBlocking: false,
    confluenceUrl: null,
    verifyUrl: null,
    verifyPoint: null,
    screenshotUrl: null,
    createdAt: '2026-07-14T09:00:00Z',
    updatedAt: '2026-07-14T09:00:00Z',
  },
  {
    id: 't9',
    title: '공공기관 할인 요금제 노출 여부 설정',
    description: '정부 및 공공기관 임직원 전용 할인 요금제의 BO 노출 여부를 ON으로 변경합니다.',
    assigneeId: 'u5',
    status: 'done',
    environment: 'prd',
    dueDate: '2026-07-30',
    isBlocking: false,
    confluenceUrl: 'https://confluence.example.com/pages/1009',
    verifyUrl: 'https://admin.prd.telecom.co.kr/plans/public-sector',
    verifyPoint: '공공기관 할인 요금제 섹션이 BO 리스트에 표시되는지 확인',
    screenshotUrl: null,
    createdAt: '2026-07-08T09:00:00Z',
    updatedAt: '2026-07-18T15:00:00Z',
  },
  {
    id: 't10',
    title: '청소년 요금제 이용 제한 연령 수정',
    description: '청소년 요금제 상한 연령을 현행 19세에서 24세로 상향 조정합니다.',
    assigneeId: 'u6',
    status: 'rejected',
    environment: 'stg',
    dueDate: '2026-08-01',
    isBlocking: false,
    confluenceUrl: 'https://confluence.example.com/pages/1010',
    verifyUrl: null,
    verifyPoint: null,
    screenshotUrl: null,
    createdAt: '2026-07-10T11:00:00Z',
    updatedAt: '2026-07-21T10:00:00Z',
  },
  {
    id: 't11',
    title: '선불 충전 만료일 정책 업데이트',
    description: '선불 요금제 충전 금액 만료 기간을 90일에서 180일로 연장합니다.',
    assigneeId: 'u2',
    status: 'in_progress',
    environment: 'dev',
    dueDate: '2026-08-03',
    isBlocking: false,
    confluenceUrl: 'https://confluence.example.com/pages/1011',
    verifyUrl: 'https://admin.dev.telecom.co.kr/prepaid/expiry-policy',
    verifyPoint: '선불 충전 만료일 정책 화면에서 유효 기간이 180일로 설정되어 있는지 확인',
    screenshotUrl: null,
    createdAt: '2026-07-15T09:00:00Z',
    updatedAt: '2026-07-19T14:00:00Z',
  },
  {
    id: 't12',
    title: '단말 보험 가입 기간 제한 설정',
    description: '단말 구매 후 보험 가입 가능 기간을 개통일로부터 14일 이내로 제한합니다.',
    assigneeId: 'u3',
    status: 'todo',
    environment: 'prd',
    dueDate: '2026-08-05',
    isBlocking: true,
    confluenceUrl: 'https://confluence.example.com/pages/1012',
    verifyUrl: null,
    verifyPoint: null,
    screenshotUrl: null,
    createdAt: '2026-07-16T10:00:00Z',
    updatedAt: '2026-07-16T10:00:00Z',
  },
  {
    id: 't13',
    title: '데이터 이월 정책 적용 플래그 변경',
    description: '잔여 데이터 이월 기능 활성화 플래그를 false에서 true로 변경합니다.',
    assigneeId: 'u4',
    status: 'review_requested',
    environment: 'prd',
    dueDate: '2026-08-07',
    isBlocking: false,
    confluenceUrl: 'https://confluence.example.com/pages/1013',
    verifyUrl: 'https://admin.prd.telecom.co.kr/data/rollover-flag',
    verifyPoint: '데이터 이월 설정 화면에서 플래그 상태가 활성화(true)로 표시되는지 확인',
    screenshotUrl: null,
    createdAt: '2026-07-17T09:00:00Z',
    updatedAt: '2026-07-20T16:00:00Z',
  },
  {
    id: 't14',
    title: '위약금 면제 사유 코드 등록',
    description: '자연재해 및 국가 재난 시 위약금 면제 처리를 위한 신규 사유 코드를 등록합니다.',
    assigneeId: 'u5',
    status: 'done',
    environment: 'dev',
    dueDate: null,
    isBlocking: false,
    confluenceUrl: 'https://confluence.example.com/pages/1014',
    verifyUrl: 'https://admin.dev.telecom.co.kr/penalty/exemption-codes',
    verifyPoint: '위약금 면제 사유 코드 목록에 "DISASTER_RELIEF" 코드가 등록되어 있는지 확인',
    screenshotUrl: null,
    createdAt: '2026-07-12T09:00:00Z',
    updatedAt: '2026-07-16T14:00:00Z',
  },
  {
    id: 't15',
    title: '우선순위 고객 상담 채널 노출 설정',
    description: 'VIP 등급 이상 고객에게 전용 상담 채널 배너를 마이페이지에 노출합니다.',
    assigneeId: 'u6',
    status: 'done',
    environment: 'stg',
    dueDate: '2026-08-10',
    isBlocking: false,
    confluenceUrl: null,
    verifyUrl: 'https://admin.stg.telecom.co.kr/cs/vip-channel',
    verifyPoint: 'VIP 고객 마이페이지에 전용 상담 채널 배너가 노출되는지 확인',
    screenshotUrl: null,
    createdAt: '2026-07-14T11:00:00Z',
    updatedAt: '2026-07-20T13:00:00Z',
  },
  {
    id: 't16',
    title: '월정액 서비스 자동 결제 안내 문구 등록',
    description: '월정액 부가서비스 자동 결제 시 앱 푸시 알림에 표시될 안내 문구를 BO에 등록합니다.',
    assigneeId: 'u2',
    status: 'in_progress',
    environment: 'stg',
    dueDate: '2026-08-12',
    isBlocking: false,
    confluenceUrl: 'https://confluence.example.com/pages/1016',
    verifyUrl: null,
    verifyPoint: null,
    screenshotUrl: null,
    createdAt: '2026-07-16T14:00:00Z',
    updatedAt: '2026-07-19T10:00:00Z',
  },
  {
    id: 't17',
    title: '5G 전용 혜택 대상 단말 목록 업데이트',
    description: '신규 출시 5G 단말 3종을 5G 전용 혜택 대상 목록에 추가합니다.',
    assigneeId: 'u3',
    status: 'rejected',
    environment: 'prd',
    dueDate: '2026-08-15',
    isBlocking: false,
    confluenceUrl: 'https://confluence.example.com/pages/1017',
    verifyUrl: null,
    verifyPoint: null,
    screenshotUrl: null,
    createdAt: '2026-07-18T09:00:00Z',
    updatedAt: '2026-07-21T09:00:00Z',
  },
  {
    id: 't18',
    title: '국내 데이터 쉐어링 정책 값 수정',
    description: '가족 쉐어링 데이터 공유 최대 용량 한도를 월 30GB에서 50GB로 상향 조정합니다.',
    assigneeId: 'u6',
    status: 'review_requested',
    environment: 'dev',
    dueDate: '2026-08-18',
    isBlocking: false,
    confluenceUrl: 'https://confluence.example.com/pages/1018',
    verifyUrl: 'https://admin.dev.telecom.co.kr/data-sharing/family-limit',
    verifyPoint: '가족 데이터 쉐어링 설정에서 월 최대 공유 한도가 50GB로 표시되는지 확인',
    screenshotUrl: null,
    createdAt: '2026-07-20T10:00:00Z',
    updatedAt: '2026-07-21T08:00:00Z',
  },
]

export const taskHistories: TaskHistory[] = [
  { id: 'h1', taskId: 't1', fromStatus: null, toStatus: 'todo', changedBy: '박지수', reason: null, createdAt: '2026-07-01T09:00:00Z' },
  { id: 'h2', taskId: 't1', fromStatus: 'todo', toStatus: 'in_progress', changedBy: '김민준', reason: null, createdAt: '2026-07-08T10:00:00Z' },
  { id: 'h3', taskId: 't2', fromStatus: null, toStatus: 'todo', changedBy: '박지수', reason: null, createdAt: '2026-07-05T10:00:00Z' },
  { id: 'h4', taskId: 't2', fromStatus: 'todo', toStatus: 'in_progress', changedBy: '이서연', reason: null, createdAt: '2026-07-12T09:00:00Z' },
  { id: 'h5', taskId: 't2', fromStatus: 'in_progress', toStatus: 'review_requested', changedBy: '이서연', reason: null, createdAt: '2026-07-17T16:00:00Z' },
  { id: 'h6', taskId: 't7', fromStatus: null, toStatus: 'todo', changedBy: '박지수', reason: null, createdAt: '2026-07-06T10:00:00Z' },
  { id: 'h7', taskId: 't7', fromStatus: 'todo', toStatus: 'in_progress', changedBy: '최도현', reason: null, createdAt: '2026-07-10T14:00:00Z' },
  { id: 'h8', taskId: 't7', fromStatus: 'in_progress', toStatus: 'rejected', changedBy: '박지수', reason: '전환 기준일 계산 방식이 기획서와 다름. 만료일 기준이 아닌 약정 시작일 기준으로 재설정 필요', createdAt: '2026-07-15T11:00:00Z' },
  { id: 'h9', taskId: 't7', fromStatus: 'rejected', toStatus: 'in_progress', changedBy: '최도현', reason: null, createdAt: '2026-07-17T09:00:00Z' },
  { id: 'h10', taskId: 't7', fromStatus: 'in_progress', toStatus: 'review_requested', changedBy: '최도현', reason: null, createdAt: '2026-07-20T11:00:00Z' },
  { id: 'h11', taskId: 't10', fromStatus: null, toStatus: 'todo', changedBy: '박지수', reason: null, createdAt: '2026-07-10T11:00:00Z' },
  { id: 'h12', taskId: 't10', fromStatus: 'todo', toStatus: 'in_progress', changedBy: '강현우', reason: null, createdAt: '2026-07-14T09:00:00Z' },
  { id: 'h13', taskId: 't10', fromStatus: 'in_progress', toStatus: 'review_requested', changedBy: '강현우', reason: null, createdAt: '2026-07-18T16:00:00Z' },
  { id: 'h14', taskId: 't10', fromStatus: 'review_requested', toStatus: 'rejected', changedBy: '박지수', reason: '연령 기준 변경은 법적 검토가 필요합니다. 법무팀 승인 문서를 첨부한 후 재요청해주세요.', createdAt: '2026-07-21T10:00:00Z' },
  { id: 'h15', taskId: 't17', fromStatus: null, toStatus: 'todo', changedBy: '박지수', reason: null, createdAt: '2026-07-18T09:00:00Z' },
  { id: 'h16', taskId: 't17', fromStatus: 'todo', toStatus: 'in_progress', changedBy: '이서연', reason: null, createdAt: '2026-07-20T10:00:00Z' },
  { id: 'h17', taskId: 't17', fromStatus: 'in_progress', toStatus: 'review_requested', changedBy: '이서연', reason: null, createdAt: '2026-07-21T08:00:00Z' },
  { id: 'h18', taskId: 't17', fromStatus: 'review_requested', toStatus: 'rejected', changedBy: '박지수', reason: '대상 단말 목록 기준이 불명확합니다. 단말 모델명과 출시일 기준을 기획서에 명시한 후 재요청 바랍니다.', createdAt: '2026-07-21T09:00:00Z' },
]

export const comments: Comment[] = [
  { id: 'c1', taskId: 't1', authorId: 'u1', body: '요금제 순서 변경 시 API 응답 캐시 갱신도 함께 진행해주세요. CDN TTL이 5분이라 반영이 늦을 수 있습니다.', createdAt: '2026-07-09T10:00:00Z' },
  { id: 'c2', taskId: 't1', authorId: 'u2', body: '확인했습니다. 캐시 퍼지 스크립트 실행 후 반영 예정입니다. 오늘 오후 작업 완료 예정입니다.', createdAt: '2026-07-09T11:30:00Z' },
  { id: 'c3', taskId: 't1', authorId: 'u1', body: '마감이 이미 지났습니다. 오늘 내로 완료 요청해주시기 바랍니다.', createdAt: '2026-07-16T09:00:00Z' },
  { id: 'c4', taskId: 't7', authorId: 'u1', body: '기획서 3페이지에 "약정 시작일 기준 30일 전"이라고 명시되어 있습니다. 현재 설정 방식을 재확인해주세요.', createdAt: '2026-07-15T10:00:00Z' },
  { id: 'c5', taskId: 't7', authorId: 'u4', body: '확인했습니다. 계산 로직을 수정하고 재설정했습니다. 다시 검토 부탁드립니다.', createdAt: '2026-07-20T11:00:00Z' },
  { id: 'c6', taskId: 't7', authorId: 'u1', body: '스테이징 환경에서 직접 확인했습니다. 이번엔 기획서와 일치합니다. 감사합니다.', createdAt: '2026-07-20T15:00:00Z' },
]

export const templates: Template[] = [
  { id: 'tpl1', name: '신규 요금제 출시 세팅', description: '신규 요금제 출시 시 필요한 BO 세팅 항목 묶음입니다.', itemCount: 5 },
  { id: 'tpl2', name: '프로모션 이벤트 세팅', description: '한정 기간 프로모션 진행 시 공통으로 필요한 세팅 항목입니다.', itemCount: 4 },
]

export const templateItems: Record<string, string[]> = {
  tpl1: ['요금제 노출 순서 설정', '가입 가능 연령 제한 등록', '혜택 우선순위 설정', '요금제 약관 버전 업데이트', '출시 일시 및 종료일 설정'],
  tpl2: ['프로모션 배너 노출 기간 설정', '프로모션 가격 등록', '대상 요금제 연결', '프로모션 종료 후 처리 설정'],
}
